version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/authentik:cached
    command: debug
  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: service:app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: docker.io/redis/redis-stack-server
    restart: unless-stopped
    network_mode: service:app

volumes:
  postgres-data:
