# Generated by Django 5.0.11 on 2025-01-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentik_core", "0043_user_force_password_change"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["force_password_change"], name="authentik_c_force_p_7245ad_idx"
            ),
        ),
    ]
