# Generated by Django 5.0.11 on 2025-01-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0044_user_authentik_c_force_p_7245ad_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="authentik_c_force_p_7245ad_idx",
        ),
    ]
